italia/design-comuni-wordpress-theme

- functions.php
- inc/actions.php
- inc/admin/options.php
- inc/admin/persona.php
- inc/admin/tipologie/tipologia_dataset.php
- inc/admin/tipologie/tipologia_documento_privato.php
- inc/admin/tipologie/tipologia_documento_pubblico.php
- inc/admin/tipologie/tipologia_evento.php
- inc/admin/tipologie/tipologia_luogo.php
- inc/admin/tipologie/tipologia_notizia.php
- inc/admin/tipologie/tipologia_servizio.php
- inc/backend-template.php
- inc/cmb2.php
- inc/lib/CMB2/init.php
- inc/utils.php
- inc/welcome.php
Ho modificato l'inclusione server side e il caricamento client side dei file sostituendo 
**get_stylesheet_directory_uri** con **get_template_directory_uri**
> Tema Conforme con l'utilizzo dei child theme

- assets/css/comuni.css
includes bugfixes for the following issues from the templates repo:
- bullet point fix 
- fix header hover
> chore: align css assets with templates

- template-parts/home/calendario.php
> fix: calendar title should be h3

- template-parts/header/header-anon.php
- template-parts/header/slimheader.php
align slimheader to static template for language dropdown
> feat: align slimheader markup to templates

- walkers/footer-info.php
- walkers/main-menu.php
- walkers/menu-header-right.php
Issue [https://github.com/italia/design-comuni-wordpress-theme/issues/33](https://github.com/italia/design-comuni-wordpress-theme/issues/33)
> fix: rimosso doppio tag chiusura </li>

- footer.php
> Sezione contatti e link in footer

- single-evento.php
- single-notizia.php
- single-servizio-old.php
- single-servizio.php
- template-parts/prenotazione/final-step.php
Fixed a typo and removed uppercase text using Bootstrap Italia classes
> fix: page index typo and uppercase

- inc/comuni_config.php
- single-notizia.php
- template-parts/common/search-modal.php
- template-parts/home/argomenti.php
- template-parts/home/notizie.php
- template-parts/home/ricerca.php
Aggiunta sezione al template Notizia per visualizzare eventuali file allegati
> Aggiunta sezione allegati al template Notizia

- inc/breadcrumb.php
- single-documento_pubblico.php
- single-servizio.php
- template-parts/single/persone.php
Implementazione del template relativo ai contenuti di tipo Documento Pubblico
Fixes #36 #52
> Caricamento documenti pubblici : implementazione del template

- single-documento_pubblico.php
- single-notizia.php
> fix: reading time

- inc/lib/CMB2-field-Leaflet-Geocoder/cmb-field-leaflet-map.php
- inc/lib/cmb-field-select2-master/cmb-field-select2.php
- inc/utils.php
- single-evento.php
- template-parts/home/messages.php
Fix: link dei file allegati non funzionante nella pagina evento.
- [ x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [ x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).
> Fix: link dei file allegati non funzionante nella pagina evento

- inc/lib/CMB2-field-Leaflet-Geocoder/cmb-field-leaflet-map.php
- inc/lib/cmb-field-select2-master/cmb-field-select2.php
- inc/utils.php
Fixes #198
- [x ] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [ x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).
> fix: revert method signature modification

- template-parts/single/punto-contatto.php
Inserito il codice per rendere attivo il link al punto di contatto
> Il template non permette il link al punto di contatto

- home.php
- inc/admin/options/pagina_home.php
- template-parts/hero/hero.php
- template-parts/home/calendario.php
- template-parts/home/notizia-evidenza.php
- template-parts/home/notizie.php
Aggiunta sezione per una notizia in evidenza fullwidth e la possibilità di impostare il numero di news in evidenza in Homepage.
Fixes #239
> Contenuti in evidenza in homepage

- template-parts/documento/cards-list.php
Fixed $tipo variable, kudos to @abmcr 
Resolves #285 #286
> fix: cards-list documento

- page.php
> fix: link to IA doc

- single.php
stato rilasciata -> stata rilasciata
> Fix: typo in single.php

- inc/welcome.php
Rimossa modifica al welcome panel di WP che presenta problemi di styling (il css utilizzato varia da versione a versione di WP) e ripristinata logica di dismiss nativa di WP
Analogo al modello scuole: https://github.com/italia/design-scuole-wordpress-theme/pull/405
> Update welcome.php - Removed welcome box with incorrect style

- single-servizio.php
Fix: change metatag name --> audienceType
> fix: metatag audience key

- inc/comuni_config.php
- template-parts/search/filters.php
- Aggiunta compabilità ricerca con plugin WP "Amministrazione Trasparente": https://it.wordpress.org/plugins/amministrazione-trasparente/
- Rimosso php warning
> Compatibilità ricerca con plugin "Amministrazione Trasparente"

- inc/comuni_config.php
- inc/comuni_tipologie.json
> fix: la ricerca di un testo venga estesa alle pagine e ai post

- inc/admin/tipologie/tipologia_documento_privato.php
- inc/admin/tipologie/tipologia_documento_pubblico.php
- page.php
- single-evento.php
- single.php
This PR fixes some templates errors:
- Child events are now correctly displayed in `single-evento.php`
- Removed `required` for 'numero protocollo' in the document content type
- Updated warning message for missing templates in `single.php` and `page.php`
- Removed default message in the template `single-evento.php`
> fix: layout errors

- inc/admin/tipologie/tipologia_documento_privato.php
- inc/admin/tipologie/tipologia_documento_pubblico.php
Removed `*` from not required fields. 
Related to #350.
Thx to @enrimk for reporting.
> Removed * from not required fields.

- home.php
- template-parts/common/search-modal.php
Fixed some accessibility issues reported in #362
> fix: accessibility issues

- page-templates/assistenza.php
Beautify html code for readability.
> fix: beautify html code

- functions.php
- inc/admin/tipologie/tipologia_documento_pubblico.php
- inc/comuni_config.php
- single-documento_pubblico.php
- template-parts/documento/card.php
- template-parts/persona/card.php
Template pagina Documento Pubblico in conformità al mockup su figma
> Template pagina Documento Pubblico

- inc/admin/persona.php
- inc/admin/tipologie/tipologia_persona_pubblica.php
- single-persona_pubblica.php
Abbiamo aggiunto il template per la persona pubblica.
Inserito il nuovo template single-persona_pubblica.php
Aggiornati i file correlati:
- inc\admin\persona.php
- inc\admin\tipologie\tipologia_persona_pubblica.php
- Le modifiche sono state verificate su Google Chrome, Firefox ed Edge e per diverse risoluzioni dello schermo.
Una pagina realizzata con questo modello è accessibile qui:
https://comune.totolabs.it/persona_pubblica/simona-monaldo/
> Template persona pubblica

- page-templates/domande-frequenti.php
- template-parts/home/calendario.php
Corretti alcuni problemi rilevati.
Corretti alcuni problemi:
La pagina "Domande Frequenti" non conteneva il modulo di valutazione.
- La modifica apportata è visualizzabile qui: https://comune.totolabs.it/domande-frequenti/
Nel codice di visualizzazione del calendario eventi gli elementi di intestazione non erano in ordine sequenziale decrescente (abbiamo sostitutito un h4 con un h3)
- La modifica apportata è visualizzabile qui: https://comune.totolabs.it/
> Corretti alcuni problemi rilevati

- template-parts/unita-organizzativa/card-full.php
> Update card-full.php (data element)

- page-templates/assistenza.php
- single-documento_pubblico.php
- single-evento.php
- single-luogo.php
- single-notizia.php
- single-persona_pubblica.php
- single-servizio.php
- template-parts/prenotazione/final-step.php
- template-parts/prenotazione/index.php
Rimuovere le classi CSS secondo l'aggiornamento previsto nella v2.4.0 dei templates statici
> fix: remove classes

- inc/utils.php
- template-parts/novita/tutte-novita.php
> fix #296 ordine crono novita

- walkers/main-menu.php
> fix: main menu active class activation
