single-evento.php
Removed from template event because it is not foreseen by the new Information Architecture.
=> Removed template part rating

archive-servizio.php, inc/utils.php, template-parts/single/more-posts-carousel.php, template-parts/single/more-posts.php
Alcune categorie non mostravano correttamente i servizi associati: ora la ricerca viene effettuata per "slug" e non per "name".
=> fix: categorie servizio

single-evento.php
This PR fixes a bug with the sticky navbar which overlays the header on mobile devices.
=> fix: navbar sticky bug

header.php, inc/admin/options/opzioni_comune.php, template-parts/common/logo-mobile.php
Aggiunta nuova funzionalità per l'inserimento di un'immagine alternativa dello stemma del comune per offcanvas.
Fix #107
=> Stemma alternativa per offcanvas

inc/utils.php, template-parts/novita/tutte-novita.php
All'interno di inc/utils.php ho creato una funzione per recuperare il timestamp delle novità _dci_get_data_pubblicazione_ts_ in modo da poter ordinare i post nel file template-parts/novita/tutte-novita.php
Questa PR fa riferimento alla issue #17
=> Ordine novità in Esplora tutte le novità

archive-servizio.php, inc/utils.php, page-templates/domande-frequenti.php, template-parts/documento/tutti-documenti.php, template-parts/novita/tutte-novita.php, template-parts/search/more-results.php, template-parts/servizio/tutti-servizi.php
C'è un comportamento inusuale in alcuni form del tema.
Il carattere slash "/" viene moltiplicato nel campo di immissione ad ogni Invio del form di ricerca.
Ad ogni invio del form lo "slash" viene moltiplicato (es. primo invio: /, secondo invio: //, terzo invio: ////, quarto invio: ////////), fino al raggiungimento del limite massimo previsto dal webserver per il metodo GET.
Il valore viene restituito nel form senza escaping, pur essendo il GET filtrato dalla funzione add_slashes di PHP, presente in wp_magic_quotes.
Step per riprodurre:
Immettere il carattere slash "/" e inviare il form.
Nel campo di immissione verrà mostrato lo slash "/" duplicato più e più volte, fino a eventuale errore e interruzione da parte del webserver (es. Error URI Request Too Large).
vedasi …
=> fix: form inputs slash bug

page-templates/prenota-appuntamento.php
Con il codice attuale si ottengono due warnings
Notice: La funzione WP_Scripts::localize è stata richiamata in maniera scorretta. Il parametro $l10n deve essere un array. Per passare dati arbitrari agli script, usa la funzione wp_add_inline_script(). Leggi [Debugging in WordPress](https://wordpress.org/documentation/article/debugging-in-wordpress/) per maggiori informazioni. (Questo messaggio è stato aggiunto nella versione 5.7.0.) in /home/au2yb3ls/pnrr.mlabvda.it/wp-includes/functions.php on line 5865
Notice: La funzione WP_Scripts::localize è stata richiamata in maniera scorretta. Il parametro $l10n deve essere un array. Per passare dati arbitrari agli script, usa la funzione wp_add_inline_script(). Leggi [Debugging in WordPress](https://wordpress.org/documentation/article/debugging-in- …
=> Update prenota-appuntamento.php per fix di warnings

functions.php, page-templates/domande-frequenti.php, search.php, template-parts/documento/tutti-documenti.php, template-parts/novita/tutte-novita.php, template-parts/servizio/tutti-servizi.php
Risolve alcuni problemi con i template delle ricerche.
FIxes #307 
Il warning php è causato da end() su un array che non può essere passato per riferimento. Fortunatamente l'array non è necessario (il che ci evita un array_key_last o un array_slice, o altre perversioni php per leggere l'ultimo elemento 😁).
Parallelamente, e sempre collegato a search/more-results.php, c'è un altro problema: in alcuni template di pagina viene alterata $wp_query con la ricerca, e all'uscita non viene ripristinata.
Anche $post in alcuni loop secondari [^1] viene settato e non ripristinato all'uscita.
Questo può causare bug non subito evidenti.
Ad es., get_parent_template() richiede che $post sia la pagina "principale", fuori dal loop. [^2]
Invece, senza un wp_reset_postdata o wp_reset_query, riceve in $post …
=> Fix issue #307 e ricerca

template-parts/luogo/card-full.php
In luogo/card-full.php, uniformate le classi css con evento/card-full.php, per correggere padding mancante.
Corregge una discrepanza di layout tra le due card, evidente nella pagina [Vivere il Comune](https://italia.github.io/design-comuni-pagine-statiche/sito/eventi.html), sez. Luoghi.
I due tipi di card dovrebbero avere lo stesso layout.
Prima:
Dopo:
- [x ] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [x ] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione- …
=> fix: Card luogo come card evento

single-documento_pubblico.php, template-parts/home/notizie.php
Sostituiti short tag php con normali open tag + echo.
Micro-correzione rapida a un paio di template. Sostituiti <?=... con <?php echo..., secondo [raccomandazioni WP](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#no-shorthand-php-tags).
Insieme alla PR #292, chiude #261 . [resolves #261]
- [ x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [ x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/ …
=> fix: PHP short tag

single-servizio.php
Nel template single-servizio.php, i metadati json-ld usano il tag php abbreviato "<?=".
Sostituiti con il tag completo "<?php echo..."
Ragione:
Gli short open tag php non sono sempre attivi, e anzi nelle installazioni WordPress dovrebbero essere sempre disattivati, perché esplicitamente contro i [coding standard](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#no-shorthand-php-tags).
Questo causa che i valori dei campi non vengano sempre visualizzati.
#261
Per alcuni campi opzionali, quando non compilati, è bene omettere l'intera riga, perché il validatore non passa valori incompleti.
- [ x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per …
=> json-ld in single-servizio: correzioni php tag e validazione

archive-argomento.php
Quickfix per un bug di layout sulla sez. hero del template Argomento.
L'ombra della sezione Hero non è applicata alla scheda bianca, ma al suo contenitore, ed è quindi disallineata, e troncata in basso. Il difetto è più evidente quando l'immagine manca, ma c'è sempre. [^1]
[^1]: In realtà, questo punto è più un bug del [layout di _pagine-statiche_](https://github.com/italia/design-comuni-pagine-statiche/blob/main/src/pages/sito/argomento.hbs), e andrebbe corretto anche là.
-> Soluzione: spostata l'ombra sul blocco interno.
Inoltre, quando manca l'immagine, [^2] non ha più senso il layout con il box bianco circondato dalla foto, e perlomeno va tolto il margine che stacca il box dal menù in alto. Rimane sempre la "sovrapposizione" dell'hero con la sezione sotto, che forse senza l'immagine …
=> Piccolo bug layout sez. Hero in dett. Argomento

functions.php
I css del tema è bene che siano caricati in ordine di specificità, dal più generico.
Riordinata l'inclusione, e specificate le dipendenze reciproche fra stylesheet.
Prima la libreria Bootstrap, poi il modulo Comuni, infine il css del tema vero e proprio.
Questo facilita le modifiche, e riduce il css necessario alle correzioni. [^1]
Specialmente utile nel caso di un child theme, il cui stylesheet di solito è accodato _dopo_ gli altri css "base", e li estende o corregge dove opportuno.
[^1]: Con chiare dipendenze, è più facile posizionare gli stylesheet. Altrimenti, se lo stylesheet child non è accodato ma sta prima degli altri che deve sovrascrivere, facilmente si è costretti ad aumentare la specificità delle regole da sovrapporre, per dargli più peso. Il che è scomodo, crea disordine e …
=> feat: Riordino inclusione stylesheet tema

inc/lib/CMB2-field-Leaflet-Geocoder/cmb-field-leaflet-map.php, inc/lib/cmb-field-select2-master/cmb-field-select2.php
Notice php causati da argomenti opzionali che ne precedono altri obbligatori, in metodi di classi CMB2.
Fixes #315 
NB: i notice [^1] sono emessi [da php >= 8.0](https://www.php.net/manual/en/migration80.deprecated.php#migration80.deprecated.core).
[^1]: Questi warning sono verosimilmente quello che si intendeva correggere [qui](https://github.com/italia/design-comuni-wordpress-theme/pull/188/commits/59ee05307265815cb4906a332249fbc96afc6891). Il che vedo che ha poi portato ai problemi di #198, e infine a un revert, ma solo perché era stato cambiato l'ordine dei parametri nella signature di funzione. In realtà basta togliere il default, lasciandoli al loro posto.
=> fix: deprecation notices in CMB2

inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/geocoder.js
Fixes #339, #340, #354
Fix trovato da @abmcr, @fnori77, @marcogangemideda
Fa seguito a un [cambiamento nella API di openstreetmap](https://github.com/osm-search/Nominatim/issues/3134).
=> fix: CMB2 Leaflet Geocoder (OSM API)

footer.php, header.php, inc/load_more.php
Fixed the `load_more` function adding different ordering upon different post types.
Default arguments set a decrescent order by date. 
Ascendent order by `post_title` is kept for all post types except 'notizia'.
Resolves #17 #136 #160 #163  #192 #332 #380 #383
=> fix: load more order

single-servizio.php
- I valori nel JSON-LD della scheda Servizio è bene che siano encodati con json_encode(), non con esc_js(), perchè nel caso di presenza di apostrofi o virgolette si potrebbe ottenere json invalido. [^1]
- Le specifiche per il JSON-LD vengono indicate sia [nella docum. dell'app valutazione, §5.21](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html#raccomandazione-r-si-1-1-metatag), sia in quella [generale del modello Comuni §2.1.10.1](https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/modello-sito-comunale/architettura-informazione.html#dati-strutturati-e-interoperabilita).  
Nella doc. generale il template è un po' più dettagliato e completo: usato quello schema.
- …
=> Servizio: correzioni json ld

inc/admin-css/style-admin.css, inc/admin/options/pagina_avvisi.php, style.css
Aggiunto un nuovo colore arancione tra le opzioni per la sezione "Avvisi in Home".
Fixes #382 
- [x ] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [ x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).
=> Feat: aggiunto il colore arancione nella pagina Avvisi in Home

inc/admin/tassonomie/tassonomia_tipi_notizia.php, taxonomy-tipi_notizia.php
Template semplificato per la tassonomia `tipi_notizia` (_Notizie_, _Comunicati_, _Avvisi_).
Lista semplice paginata, secondo il layout della sez. "Esplora" del template [Lista risorse](https://italia.github.io/design-comuni-pagine-statiche/sito/lista-risorse.html), ma senza campo ricerca.
---
=> Template archivio Tipi Notizia

inc/breadcrumb.php
Aggiunta di un filtro per consentire a funzioni e plugin terzi di variare il risultato dei breadcrumb, ad esempio aggiungendo prefissi o sezioni in alcuni livelli.
Esempio di utilizzo:
```
add_filter( 'dci_get_breadcrumb_items',  'my_test_function', 10, 2 );
function my_test_function( $items ) {     
$items[] =  "<a href='URL'>TITLE</a>";
return $items;
}
```
=> Third party breadcrumb filter

inc/admin/options.php, inc/admin/options/pagina_luoghi.php, inc/comuni_pagine.json, inc/load_more.php, page-templates/luoghi.php, template-parts/luogo/evidenza.php, template-parts/luogo/tutti-luoghi.php, template-parts/vivere-comune/luoghi.php
Realizzato il nuovo template per "Tutti i luoghi".
Nel dettaglio:
- aggiunto il template "Tutti i luoghi"
https://comune.totolabs.it/vivere-il-comune/luoghi/
- aggiunta la scheda "Luoghi" nel pannello di configurazione del tema", con possibilità di impostare immagine/banner e didascali "hero" e luoghi in evidenza
- aggiunte le relative card previste per una corretta visualizzazione dei luoghi
- aggiunta la pagina "I luoghi" tra le pagine predefinite, la quale utilizza il template creato
- modificato il collegamento nella pagina "Vivere il comune" del pulsante "Tutti i luoghi" con l'aggiunta della nuova pagina
https://comune.totolabs.it/vivere-il-comune/
=> Template "tutti i luoghi"

single-luogo.php, template-parts/luogo/card-light.php, template-parts/unita-organizzativa/card.php
Creato il template per i luoghi.
Abbiamo aggiunto il nuovo template per i luoghi, con la relativa card
Un esempio: https://comune.totolabs.it/vivere-il-comune/luoghi/colosseo/
Corretta la card, utilizzata nel template, per le unità organizzative (gli indirizzi non venivano mostrati correttamente).
=> Nuovo template Single Luogo

inc/comuni_pagine.json
Nella v1.10.0, il formato del JSON che dichiara l lista delle pagine predefinite non è corretto: viene restituita una lista nulla, e dunque le pagine predefinite 1) non sono create in una nuova installazione, o 2) non sono riconosciute in una installazione esistente.
La PR corregge il file, e ripristina le funzionalità che ne dipendono.
Fixes #439
=> fix: Json pagine predefinite

inc/admin/tassonomie/tassonomia_tipi_doc_albo_pretorio.php, inc/admin/tassonomie/tassonomia_tipi_documento.php, taxonomy-tipi_documento.php
Ho aggiunto il nuovo template sul tipo_documento, feature già presente per la tipologia notizie 
Esempio: https://www.comune.ali.me.it/tipi_documento/documento-funzionamento-interno/
Un esempio per lo slug: https://comune.nomecomune.me.it/tipi_documento/documento-di-programmazione-e-rendicontazione/
Ho usato il file taxonomy-tipi_notizia.php come esempio per poter creare il template e ho abilitato l'archivio nel backend del template.
=> Fix pagina tipologia documento, relativo alla issue #404

inc/utils.php, single-documento_pubblico.php, template-parts/domanda-frequente/item.php
Correzioni veloci per risolvere alcuni bug minori segnalati tempo fa, e tuttora presenti.
Il _postmeta_ "risposta" non viene prelevato.
`$documenti_collegati` è già in origine un array di post ID, e non di url che debbano essere convertiti in post.
Nel loop si ottiene sempre un `get_post(null)`, cioè sempre il documento corrente.
Piccolo bug in `dci_get_related_unita_amministrative()`.
Prima [qui preleva i servizi come lista di ID](https://github.com/italia/design-comuni-wordpress-theme/blob/80f7c859163b19a3e8861596a1bca57d1422bf48/inc/utils.php#L1067), e poi [qui li usa come oggetti post](https://github.com/italia/design-comuni-wordpress-theme/blob/80f7c859163b19a3e8861596a1bca57d1422bf48/inc/utils.php#L1094).
=> Quickfix: alcuni piccoli bug

inc/activation.php
Correzioni all'assegnazione di template e slug delle pagine predefinite.
---
La procedura che crea le pagine predefinite configurate in [comuni_pagine.json](https://github.com/italia/design-comuni-wordpress-theme/blob/main/inc/comuni_pagine.json) ha questi difetti:
1) se non hanno un template assegnato, gli viene attribuito un template "rotto" (invece di nessun template);
2) lo slug dichiarato non viene in realtà applicato, viene ignorato e se ne assegna uno formato a partire dal titolo.[^1]
[^1]: A volte lo slug risulta uguale o simile, ma non sempre.  [ "post_slug" non è un parametro di wp_insert_post() ]
Fixes #425
=> Fix: Creazione pagine predefinite

inc/admin/page.php, inc/comuni_config.php, inc/comuni_tipologie.json, inc/utils.php, template-parts/home/messages.php, template-parts/search/filters-modal.php
Risolve alcuni warning php segnalati in vecchi issue, e certi difetti correlati.
Fixes #267, fixes #302, fixes #449.
Inoltre, risolve i warning introdotti con la #349, descritti [qui](https://github.com/italia/design-comuni-wordpress-theme/issues/271#issuecomment-1729338428).
=> Vari warning php  

single-servizio.php
Fix che risolve un problema della pagina single-servizio.php.
Il modello non era conforme al Criterio C.SI. 1.3: non era presente un tag <div> con data-element="service-area" che identifica i contatti (https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html).
Abbiamo aggiunto il tag mancante.
Un esempio è visualizzabile qui: https://comune.totolabs.it/servizio/anagrafe-e-stato-civile/
- [ x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [ x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" …
=> Fix single-servizio.php
